CREATE TABLE IF NOT EXISTS word (
    id       INTEGER NOT NULL PRIMARY KEY,
    word     TEXT NOT NULL UNIQUE,
    parent   INTEGER,
    priority INTEGER NOT NULL,
    status   TEXT NOT NULL NOT NULL,
    FOREIGN KEY (parent) REFERENCES word(id),
    CHECK (status IN ("WAITING_FOR_GENERATION", "GENERATING", "GENERATION_COMPLETE", "WAITING_FOR_CLASSIFICATION", "CLASSIFYING", "CLASSIFIED_AS_INVALID", "WAITING_FOR_SEARCH", "SEARCHING", "SEARCH_COMPLETE")) 
);

CREATE TABLE IF NOT EXISTS link (
    id       INTEGER NOT NULL PRIMARY KEY,
    word     INTEGER NOT NULL,
    title    TEXT NOT NULL,
    link     TEXT NOT NULL,
    priority INTEGER NOT NULL,
    status   TEXT NOT NULL,
    FOREIGN KEY (word) REFERENCES word(id),
    CHECK (status IN ("WAITING_FOR_DOWNLOAD", "DOWNLOADING", "DOWNLOAD_COMPLETE"))
);

--CREATE TABLE IF NOT EXISTS page (
--    id       INTEGER NOT NULL PRIMARY KEY,
--    link     INTEGER NOT NULL,
--    content  TEXT NOT NULL,
--    priority INTEGER NOT NULL,
--    status   TEXT NOT NULL,
--    FOREIGN KEY (word) REFERENCES word(id),
--    CHECK (status IN ("WAITING_FOR_EXTRACTION", "EXTRACTING", "EXTRACTION_COMPLETE"))
--);

