import csv
import redis

#r = redis.Redis(
#    host='localhost', 
#    port=6383, 
#    db=0,
#)

[Energy (Atwater General Factors), KCAL]
[Energy (Atwater Specific Factors), KCAL]
[Solids, G]
[Nitrogen, G]
[Protein, G]
[Total lipid (fat), G]
[Carbohydrate, by difference, G]
[Fiber, crude (DO NOT USE - Archived), G]
[Ash, G]
[Energy, KCAL]
[Starch, G]
[Sucrose, G]
[Glucose, G]
[Fructose, G]
[Lactose, G]
[Maltose, G]
[Amylose, G]
[Amylopectin, G]
[Pectin, G]
[Alcohol, ethyl, G]
[Pentosan, G]
[Pentoses, G]
[Hemicellulose, G]
[Cellulose, G]
[pH, PH]
[Specific Gravity, SP_GR]
[Organic acids, G]
[Acetic acid, MG]
[Aconitic acid, MG]
[Benzoic acid, MG]
[Chelidonic acid, MG]
[Chlorogenic acid, MG]
[Cinnamic acid, MG]
[Citric acid, MG]
[Fumaric acid, MG]
[Galacturonic acid, MG]
[Gallic acid, MG]
[Glycolic acid, MG]
[Isocitric acid, MG]
[Lactic acid, MG]
[Malic acid, MG]
[Oxaloacetic acid, MG]
[Oxalic acid, MG]
[Phytic acid, MG]
[Pyruvic acid, MG]
[Quinic acid, MG]
[Salicylic acid, MG]
[Succinic acid, MG]
[Tartaric acid, MG]
[Ursolic acid, MG]
[Solids, non-fat, G]
[Carbohydrate, by summation, G]
[Water, G]
[Adjusted Nitrogen, G]
[Adjusted Protein, G]
[Piperine, G]
[Mannitol, G]
[Sorbitol, G]
[Caffeine, MG]
[Theobromine, MG]
[Nitrates, MG]
[Nitrites, MG]
[Nitrosamine,total, MG]
[Energy, kJ]
[Sugars, Total, G]
[Solids, soluble, G]
[Glycogen, G]
[Fiber, neutral detergent (DO NOT USE - Archived), G]
[Reducing sugars, G]
[Beta-glucans, G]
[Oligosaccharides, G]
[Nonstarch polysaccharides, G]
[Resistant starch, G]
[Carbohydrate, other, G]
[Arabinose, G]
[Xylose, G]
[Galactose, G]
[Raffinose, G]
[Stachyose, G]
[Xylitol, G]
[Fiber, total dietary, G]
[Lignin, G]
[Ribose, G]
[Fiber, soluble, G]
[Theophylline, MG]
[Fiber, insoluble, G]
[Total fat (NLEA), G]
[Total sugar alcohols, G]
[Calcium, Ca, MG]
[Chlorine, Cl, MG]
[Iron, Fe, MG]
[Magnesium, Mg, MG]
[Phosphorus, P, MG]
[Potassium, K, MG]
[Sodium, Na, MG]
[Sulfur, S, MG]
[Zinc, Zn, MG]
[Chromium, Cr, UG]
[Cobalt, Co, UG]
[Copper, Cu, MG]
[Fluoride, F, UG]
[Iodine, I, UG]
[Manganese, Mn, MG]
[Molybdenum, Mo, UG]
[Selenium, Se, UG]
[Vitamin A, IU, IU]
[Retinol, UG]
[Vitamin A, RAE, UG]
[Carotene, beta, UG]
[Carotene, alpha, UG]
[Vitamin E (alpha-tocopherol), MG]
[Vitamin D (D2 + D3), International Units, IU]
[Vitamin D2 (ergocalciferol), UG]
[Vitamin D3 (cholecalciferol), UG]
[25-hydroxycholecalciferol, UG]
[Vitamin D (D2 + D3), UG]
[25-hydroxyergocalciferol, UG]
[Phytoene, UG]
[Phytofluene, UG]
[Carotene, gamma, UG]
[Zeaxanthin, UG]
[Cryptoxanthin, beta, UG]
[Lutein, UG]
[Lycopene, UG]
[Lutein + zeaxanthin, UG]
[Vitamin E (label entry primarily), IU]
[Tocopherol, beta, MG]
[Tocopherol, gamma, MG]
[Tocopherol, delta, MG]
[Tocotrienol, alpha, MG]
[Tocotrienol, beta, MG]
[Tocotrienol, gamma, MG]
[Tocotrienol, delta, MG]
[Aluminum, Al, UG]
[Antimony, Sb, UG]
[Arsenic, As, UG]
[Barium, Ba, UG]
[Beryllium, Be, UG]
[Boron, B, UG]
[Bromine, Br, UG]
[Cadmium, Cd, UG]
[Gold, Au, UG]
[Iron, heme, MG]
[Iron, non-heme, MG]
[Lead, Pb, UG]
[Lithium, Li, UG]
[Mercury, Hg, UG]
[Nickel, Ni, UG]
[Rubidium, Rb, UG]
[Fluoride - DO NOT USE; use 313, UG]
[Salt, NaCl, MG]
[Silicon, Si, UG]
[Silver, Ag, UG]
[Strontium, Sr, UG]
[Tin, Sn, UG]
[Titanium, Ti, UG]
[Vanadium, V, UG]
[Vitamin A, RE, MCG_RE]
[Carotene, MCG_RE]
[Vitamin E, MG_ATE]
[cis-beta-Carotene, UG]
[cis-Lycopene, UG]
[cis-Lutein/Zeaxanthin, UG]
[Vitamin C, total ascorbic acid, MG]
[Vitamin C, reduced ascorbic acid, MG]
[Vitamin C, dehydro ascorbic acid, MG]
[Thiamin, MG]
[Riboflavin, MG]
[Niacin, MG]
[Niacin from tryptophan, determined, MG]
[Niacin equivalent N406 +N407, MG]
[Pantothenic acid, MG]
[Vitamin B-6, pyridoxine, alcohol form, MG]
[Vitamin B-6, pyridoxal, aldehyde form, MG]
[Vitamin B-6, pyridoxamine, amine form, MG]
[Vitamin B-6, N411 + N412 +N413, MG]
[Vitamin B-6, MG]
[Biotin, UG]
[Folate, total, UG]
[Vitamin B-12, UG]
[Folate, free, UG]
[Choline, total, MG]
[Inositol, MG]
[Inositol phosphate, MG]
[Vitamin K (Menaquinone-4), UG]
[Vitamin K (Dihydrophylloquinone), UG]
[Vitamin K (phylloquinone), UG]
[Folic acid, UG]
[Folate, food, UG]
[5-methyl tetrahydrofolate (5-MTHF), UG]
[Folate, not 5-MTHF, UG]
[Folate, DFE, UG]
[10-Formyl folic acid (10HCOFA), UG]
[5-Formyltetrahydrofolic acid (5-HCOH4, UG]
[Tetrahydrofolic acid (THF), UG]
[Choline, free, MG]
[Choline, from phosphocholine, MG]
[Choline, from phosphotidyl choline, MG]
[Choline, from glycerophosphocholine, MG]
[Betaine, MG]
[Choline, from sphingomyelin, MG]
[p-Hydroxy benzoic acid, MG]
[Caffeic acid, MG]
[p-Coumaric acid, MG]
[Ellagic acid, MG]
[Ferrulic acid, MG]
[Gentisic acid, MG]
[Tyrosol, MG]
[Vanillic acid, MG]
[Phenolic acids, total, MG]
[Polyphenols, total, MG]
[Tryptophan, G]
[Threonine, G]
[Isoleucine, G]
[Leucine, G]
[Lysine, G]
[Methionine, G]
[Cystine, G]
[Phenylalanine, G]
[Tyrosine, G]
[Valine, G]
[Arginine, G]
[Histidine, G]
[Alanine, G]
[Aspartic acid, G]
[Glutamic acid, G]
[Glycine, G]
[Proline, G]
[Serine, G]
[Hydroxyproline, G]
[Cysteine and methionine(sulfer containig AA), G]
[Phenylalanine and tyrosine (aromatic  AA), G]
[Asparagine, G]
[Cysteine, G]
[Glutamine, G]
[Taurine, G]
[Sugars, added, G]
[Sugars, intrinsic, G]
[Calcium, added, MG]
[Iron, added, MG]
[Calcium, intrinsic, MG]
[Iron, intrinsic, MG]
[Vitamin C, added, MG]
[Vitamin E, added, MG]
[Thiamin, added, MG]
[Riboflavin, added, MG]
[Niacin, added, MG]
[Vitamin B-12, added, UG]
[Vitamin C, intrinsic, MG]
[Vitamin E, intrinsic, MG]
[Thiamin, intrinsic, MG]
[Riboflavin, intrinsic, MG]
[Niacin, intrinsic, MG]
[Vitamin B-12, intrinsic, UG]
[Cholesterol, MG]
[Glycerides, G]
[Phospholipids, G]
[Glycolipids, G]
[Fatty acids, total trans, G]
[Fatty acids, total saturated, G]
[SFA 4:0, G]
[SFA 6:0, G]
[SFA 8:0, G]
[SFA 10:0, G]
[SFA 12:0, G]
[SFA 14:0, G]
[SFA 16:0, G]
[SFA 18:0, G]
[SFA 20:0, G]
[MUFA 18:1, G]
[PUFA 18:2, G]
[PUFA 18:3, G]
[PUFA 20:4, G]
[PUFA 22:6 n-3 (DHA), G]
[SFA 22:0, G]
[MUFA 14:1, G]
[MUFA 16:1, G]
[PUFA 18:4, G]
[MUFA 20:1, G]
[PUFA 20:5 n-3 (EPA), G]
[MUFA 22:1, G]
[PUFA 22:5 n-3 (DPA), G]
[TFA 14:1 t, G]
[Phytosterols, MG]
[Ergosterol, MG]
[Stigmasterol, MG]
[Campesterol, MG]
[Brassicasterol, MG]
[Beta-sitosterol, MG]
[Campestanol, MG]
[Unsaponifiable matter (lipids), G]
[Fatty acids, other than 607-615, 617-621, 624-632, 652-654, 686-689), G]
[Fatty acids, total monounsaturated, G]
[Fatty acids, total polyunsaturated, G]
[Beta-sitostanol, MG]
[Delta-7-avenasterol, MG]
[Delta-5-avenasterol, MG]
[Alpha-spinasterol, MG]
[Phytosterols, other, MG]
[SFA 15:0, G]
[SFA 17:0, G]
[SFA 24:0, G]
[Wax Esters(Total Wax), G]
[TFA 16:1 t, G]
[TFA 18:1 t, G]
[TFA 22:1 t, G]
[TFA 18:2 t not further defined, G]
[PUFA 18:2 i, G]
[PUFA 18:2 t,c, G]
[PUFA 18:2 c,t, G]
[TFA 18:2 t,t, G]
[PUFA 18:2 CLAs, G]
[MUFA 24:1 c, G]
[PUFA 20:2 n-6 c,c, G]
[MUFA 16:1 c, G]
[MUFA 18:1 c, G]
[PUFA 18:2 n-6 c,c, G]
[MUFA 22:1 c, G]
[Fatty acids, saturated, other, G]
[Fatty acids, monounsat., other, G]
[Fatty acids, polyunsat., other, G]
[PUFA 18:3 n-6 c,c,c, G]
[SFA 19:0, G]
[MUFA 17:1, G]
[PUFA 16:2, G]
[PUFA 20:3, G]
[Fatty acids, total sat., NLEA, G]
[Fatty acids, total monounsat., NLEA, G]
[Fatty acids, total polyunsat., NLEA, G]
[Fatty acids, total trans-monoenoic, G]
[Fatty acids, total trans-dienoic, G]
[Fatty acids, total trans-polyenoic, G]
[SFA 13:0, G]
[MUFA 15:1, G]
[PUFA 22:2, G]
[SFA 11:0, G]
[ORAC, Hydrophyllic, UMOL_TE]
[ORAC, Lipophillic, UMOL_TE]
[ORAC, Total, UMOL_TE]
[Total Phenolics, MG_GAE]
[Daidzein, MG]
[Genistein, MG]
[Glycitein, MG]
[Isoflavones, MG]
[Biochanin A, MG]
[Formononetin, MG]
[Coumestrol, MG]
[Flavonoids, total, MG]
[Anthocyanidins, MG]
[Cyanidin, MG]
[Proanthocyanidin (dimer-A linkage), MG]
[Proanthocyanidin monomers, MG]
[Proanthocyanidin dimers, MG]
[Proanthocyanidin trimers, MG]
[Proanthocyanidin 4-6mers, MG]
[Proanthocyanidin 7-10mers, MG]
[Proanthocyanidin polymers (>10mers), MG]
[Delphinidin, MG]
[Malvidin, MG]
[Pelargonidin, MG]
[Peonidin, MG]
[Petunidin, MG]
[Flavans, total, MG]
[Catechins, total, MG]
[Catechin, MG]
[Epigallocatechin, MG]
[Epicatechin, MG]
[Epicatechin-3-gallate, MG]
[Epigallocatechin-3-gallate, MG]
[Procyanidins, total, MG]
[Theaflavins, MG]
[Thearubigins, MG]
[Flavanones, total, MG]
[Eriodictyol, MG]
[Hesperetin, MG]
[Isosakuranetin, MG]
[Liquiritigenin, MG]
[Naringenin, MG]
[Flavones, total, MG]
[Apigenin, MG]
[Chrysoeriol, MG]
[Diosmetin, MG]
[Luteolin, MG]
[Nobiletin, MG]
[Sinensetin, MG]
[Tangeretin, MG]
[Flavonols, total, MG]
[Isorhamnetin, MG]
[Kaempferol, MG]
[Limocitrin, MG]
[Myricetin, MG]
[Quercetin, MG]
[Theogallin, MG]
[Theaflavin -3,3' -digallate, MG]
[Theaflavin -3' -gallate, MG]
[Theaflavin -3 -gallate, MG]
[(+) -Gallo catechin, MG]
[(+)-Catechin 3-gallate, MG]
[(+)-Gallocatechin 3-gallate, MG]
[Mannose, G]
[Triose, G]
[Tetrose, G]
[Other Saccharides, G]
[Inulin, G]
[PUFA 18:3 n-3 c,c,c (ALA), G]
[PUFA 20:3 n-3, G]
[PUFA 20:3 n-6, G]
[PUFA 20:4 n-3, G]
[PUFA 20:4 n-6, G]
[PUFA 18:3i, G]
[PUFA 21:5, G]
[PUFA 22:4, G]
[MUFA 18:1-11 t (18:1t n-7), G]
[MUFA 18:1-11 c (18:1c n-7), G]
[PUFA 20:3 n-9, G]
[Total Sugars, G]
[SFA 5:0, G]
[SFA 7:0, G]
[SFA 9:0, G]
[SFA 21:0, G]
[SFA 23:0, G]
[MUFA 12:1, G]
[MUFA 14:1 c, G]
[MUFA 17:1 c, G]
[TFA 17:1 t, G]
[MUFA 20:1 c, G]
[TFA 20:1 t, G]
[MUFA 22:1 n-9, G]
[MUFA 22:1 n-11, G]
[PUFA 18:2 c, G]
[TFA 18:2 t, G]
[PUFA 18:3 c, G]
[TFA 18:3 t, G]
[PUFA 20:3 c, G]
[PUFA 22:3, G]
[PUFA 20:4c, G]
[PUFA 20:5c, G]
[PUFA 22:5 c, G]
[PUFA 22:6 c, G]
[PUFA 20:2 c, G]
[Proximate, G]
[trans-beta-Carotene, UG]
[trans-Lycopene, UG]
[Cryptoxanthin, alpha, UG]
[Total dietary fiber (AOAC 2011.25), G]
[Insoluble dietary fiber (IDF), G]
[Soluble dietary fiber (SDFP+SDFS), G]
[Soluble dietary fiber (SDFP), G]
[Soluble dietary fiber (SDFS), G]
[High Molecular Weight Dietary Fiber (HMWDF), G]
[Carbohydrates, G]
[Other carotenoids, UG]
[Tocopherols and tocotrienols, MG]
[Amino acids, G]
[Minerals, MG]
[Lipids, G]
[Proximates, G]
[Vitamins and Other Components, G]
[Oligosaccharides, MG]
[Daidzin, MG]
[Genistin, MG]
[Glycitin, MG]
[Low Molecular Weight Dietary Fiber (LMWDF), G]
[Vitamin E, MG]
[Vitamin A, UG]
[Glutathione, MG]

allowed_nutrients = []

nutrients = {}
with open("nutrient.csv", "r") as file:
    csv_reader = csv.reader(file)
    fields = next(csv_reader)
    for row in csv_reader:
        id = row[3]
        name = row[1]
        unit = row[2]
        nutrients[id] = [name, unit]
        #r.hset("nutrient:unit", name, unit)
x = ""
for k, v in nutrients.items():
    x += "[" + v[0] + ", " + v[1] + "] "
print(x)

ingredients = {}
with open("fndds_ingredient_nutrient_value.csv", "r") as file:
    csv_reader = csv.reader(file)
    fields = next(csv_reader)
    for row in csv_reader:
        description = row[1]
        nutrient = nutrients[row[2]]
        value = row[3]
        kind = row[4]
        if kind != "Foundation" and kind != "SR Legacy":
            continue
        if not description in ingredients:
            ingredients[description] = { "type": kind }
        ingredients[description][nutrient] = value

id = 0
for ingredient, nutrient_map in ingredients.items():
    #print(id, ingredient)
    #for nutrient, value in nutrient_map.items():
        #r.hset(f"ingredient:{id}:nutrients", nutrient, value)
        #print(f"ingredient:{id}:nutrients " + nutrient + " " + value)
    #r.set(f"ingredient:{id}:type", nutrient_map["type"])
    #print(f"ingredient:{id}:type", nutrient_map["type"])
    id += 1

